name: Biome Lint

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Biome
        uses: biomejs/setup-biome@v2.2.1
        with:
          version: latest

      - name: Run Biome
        run: biome ci .